### ISSUE TITLE
Numbers in variables are coloured as if they were number literals.

### ISSUE THREAD

**Issue by onelivesleft** [mimhufford/jai-language-support#4]
Hopefully an easy fix?

**Comment by mimhufford** [comment]
I won't get chance to work on this myself for at least a week I'm afraid, it should just be a case of bulking up the regex [here](https://github.com/mimhufford/jai-language-support/blob/master/syntaxes/jai.tmLanguage.json#L51) though if you want to give it a go and send a PR?

**Comment by mimhufford** [comment]
Fixed and republished extension 😃

Probably still a few edge cases but much better, plus there's support for binary and hex numbers too.
